### ISSUE TITLE
Logo Design Proposal 

### ISSUE THREAD

**Issue by Tobaloidee** [itzmeanjan/sensorz#1]
hello @itzmeanjan Here's what I came up with SensorZ.. I hope you like it!

- Simple and Uniform to the other Z project logos of yours. The design is a combination of the Sensor symbol and Z initial.. Colors are based from the actual projects screenshots

![PRES-01-01-19](https://user-images.githubusercontent.com/36028424/57316177-c4be9b80-7127-11e9-8075-860bf129d519.png)

**Comment by itzmeanjan** [comment]
Now this one looks real cool :+1: 

Could you please also make icons for this app, so that I can rebuild it with newly designed icon ?

Thanks mate :)

**Comment by Tobaloidee** [comment]
Will do for sure!! 😊

**Comment by Tobaloidee** [comment]
Here's the PR #2 with the logo upload and readme update @itzmeanjan 

all other version & file formats you can download [HERE](https://drive.google.com/drive/u/0/folders/18ygdE1CBO4x7J4quTkgPfd1ROtrn5Hfw)

I will work on your other project next! 👍

**Comment by itzmeanjan** [comment]
And merging done :)

Great work  @Tobaloidee  :+1:
